generated_by: generate_config.py
generated_on: '2026-03-05T17:49:24.327475'
scenarios:
- name: Scenario 1
  generated_by: generate_config.py
  generated_on: '2026-03-05T17:49:24.327475'
  ECUs:
  - name: ECU0
    capacity: 180
  - name: ECU1
    capacity: 75
  - name: ECU2
    capacity: 160
  - name: ECU3
    capacity: 140
  - name: ECU4
    capacity: 195
  - name: ECU5
    capacity: 150
  - name: ECU6
    capacity: 115
  - name: ECU7
    capacity: 120
  - name: ECU8
    capacity: 135
  - name: ECU9
    capacity: 80
  SVCs:
  - name: SVC0
    requirement: 35
  - name: SVC1
    requirement: 55
  - name: SVC2
    requirement: 20
  - name: SVC3
    requirement: 80
  - name: SVC4
    requirement: 40
  - name: SVC5
    requirement: 90
  - name: SVC6
    requirement: 70
  - name: SVC7
    requirement: 95
  - name: SVC8
    requirement: 45
  - name: SVC9
    requirement: 65
- name: Scenario 2
  generated_by: generate_config.py
  generated_on: '2026-03-05T17:49:24.327475'
  ECUs:
  - name: ECU0
    capacity: 170
  - name: ECU1
    capacity: 175
  - name: ECU2
    capacity: 60
  - name: ECU3
    capacity: 70
  - name: ECU4
    capacity: 115
  - name: ECU5
    capacity: 165
  - name: ECU6
    capacity: 185
  - name: ECU7
    capacity: 180
  - name: ECU8
    capacity: 125
  - name: ECU9
    capacity: 120
  SVCs:
  - name: SVC0
    requirement: 50
  - name: SVC1
    requirement: 75
  - name: SVC2
    requirement: 25
  - name: SVC3
    requirement: 35
  - name: SVC4
    requirement: 95
  - name: SVC5
    requirement: 70
  - name: SVC6
    requirement: 60
  - name: SVC7
    requirement: 20
  - name: SVC8
    requirement: 55
  - name: SVC9
    requirement: 15
- name: Scenario 3
  generated_by: generate_config.py
  generated_on: '2026-03-05T17:49:24.327475'
  ECUs:
  - name: ECU0
    capacity: 160
  - name: ECU1
    capacity: 120
  - name: ECU2
    capacity: 70
  - name: ECU3
    capacity: 110
  - name: ECU4
    capacity: 150
  - name: ECU5
    capacity: 195
  - name: ECU6
    capacity: 125
  - name: ECU7
    capacity: 180
  - name: ECU8
    capacity: 115
  - name: ECU9
    capacity: 80
  SVCs:
  - name: SVC0
    requirement: 70
  - name: SVC1
    requirement: 65
  - name: SVC2
    requirement: 85
  - name: SVC3
    requirement: 15
  - name: SVC4
    requirement: 50
  - name: SVC5
    requirement: 10
  - name: SVC6
    requirement: 60
  - name: SVC7
    requirement: 20
  - name: SVC8
    requirement: 40
  - name: SVC9
    requirement: 55
- name: Scenario 4
  generated_by: generate_config.py
  generated_on: '2026-03-05T17:49:24.327475'
  ECUs:
  - name: ECU0
    capacity: 95
  - name: ECU1
    capacity: 160
  - name: ECU2
    capacity: 145
  - name: ECU3
    capacity: 125
  - name: ECU4
    capacity: 190
  - name: ECU5
    capacity: 100
  - name: ECU6
    capacity: 50
  - name: ECU7
    capacity: 120
  - name: ECU8
    capacity: 90
  - name: ECU9
    capacity: 60
  SVCs:
  - name: SVC0
    requirement: 15
  - name: SVC1
    requirement: 20
  - name: SVC2
    requirement: 40
  - name: SVC3
    requirement: 95
  - name: SVC4
    requirement: 75
  - name: SVC5
    requirement: 35
  - name: SVC6
    requirement: 80
  - name: SVC7
    requirement: 70
  - name: SVC8
    requirement: 90
  - name: SVC9
    requirement: 50
- name: Scenario 5
  generated_by: generate_config.py
  generated_on: '2026-03-05T17:49:24.327475'
  ECUs:
  - name: ECU0
    capacity: 185
  - name: ECU1
    capacity: 150
  - name: ECU2
    capacity: 85
  - name: ECU3
    capacity: 100
  - name: ECU4
    capacity: 120
  - name: ECU5
    capacity: 65
  - name: ECU6
    capacity: 135
  - name: ECU7
    capacity: 105
  - name: ECU8
    capacity: 180
  - name: ECU9
    capacity: 95
  SVCs:
  - name: SVC0
    requirement: 60
  - name: SVC1
    requirement: 50
  - name: SVC2
    requirement: 85
  - name: SVC3
    requirement: 65
  - name: SVC4
    requirement: 90
  - name: SVC5
    requirement: 10
  - name: SVC6
    requirement: 25
  - name: SVC7
    requirement: 35
  - name: SVC8
    requirement: 95
  - name: SVC9
    requirement: 40
